# -*- coding: utf-8 -*-
"""EDA_Uber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAFj6hB4dpk-VNAekcPYPQtG7YYYgQd8
"""

import pandas as pd
df=pd.read_csv("uber.csv")

df.head()

df.shape

df.info()

df.describe

df = df.drop(columns=["Unnamed: 0", "key"])

df = df.dropna()

df.info()

df.shape

# CONVERT TO DATE TIME
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

df['hour'] = df['pickup_datetime'].dt.hour        #  (0-23)
df['day'] = df['pickup_datetime'].dt.day          # DAYSر
df['month'] = df['pickup_datetime'].dt.month      #  (1-12) MONTH
df['day_of_week'] = df['pickup_datetime'].dt.weekday
df.drop(["pickup_datetime"],axis=1,inplace=True)
df.head()

import numpy as np

def haversine_distance(lon1, lat1, lon2, lat2):

    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    d_lon = lon2 - lon1
    d_lat = lat2 - lat1

    # haversin equation
    a = np.sin(d_lat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(d_lon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))

    km = 6371 * c
    return km

df['distance_km'] = haversine_distance(df['pickup_longitude'], df['pickup_latitude'],
                                         df['dropoff_longitude'], df['dropoff_latitude'])

df.head()

df.describe() ## to determine  outliers

import matplotlib.pyplot as plt
import seaborn as sns

# Select numeric features for visualization
plt.figure(figsize=(12, 6))
sns.boxplot(data=df)
plt.title("Boxplot for All Numeric Features")
plt.xticks(rotation=45)
plt.show()

# filtering the data outliers
df = df[
    (df['fare_amount'] > 0) &             # PRICE MUST BE GREATER THAN ZERO
    (df['passenger_count'] > 0) &           # NO. OF PASSENGERS IS GREATER THAN ZERO
    (df['passenger_count'] <= 5) &          # NO. OF PASSENGER IS LESS THAN 5 (MAX)
    (df['distance_km'] > 0) &               # DISTANCE IN KM MUST BE GREATER THAN 0
    (df['distance_km'] < 100) &             # MAX DISTANCE LESS THAN 100 KM       (LOGIC)
    (df['pickup_latitude'] > 40) & (df['pickup_latitude'] < 42) & # TRIPS WITHIN New York
    (df['pickup_longitude'] > -75) & (df['pickup_longitude'] < -72)
]

print( df.shape)

# After filtering outliers (BOXplot All numeric features )
import matplotlib.pyplot as plt
import seaborn as sns

# Select numeric features for visualization
plt.figure(figsize=(12, 6))
sns.boxplot(data=df)
plt.title("Boxplot for All Numeric Features")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df.sample(5000, random_state=42), x='distance_km', y='fare_amount', alpha=0.5, color='purple')
plt.title('Trip Distance vs Fare Amount')
plt.xlabel('Distance (km)')
plt.ylabel('Fare Amount ($)')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Columns to visualize
location_cols = ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']

plt.figure(figsize=(15, 10))

for i, col in enumerate(location_cols):
    plt.subplot(2, 2, i + 1) # Create a 2x2 grid of subplots
    sns.histplot(df[col].dropna(), kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

"""they are normally distributed --> so we will apply standardization"""

from sklearn.preprocessing import StandardScaler

# Columns to standardize
location_cols_to_standardize = ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply standardization to the selected columns
df[location_cols_to_standardize] = scaler.fit_transform(df[location_cols_to_standardize])

print("DataFrame after standardization of location columns:")
df.head()

df.describe()

# Remove outliers from 'fare_amount'
Q1_fare = df['fare_amount'].quantile(0.25)
Q3_fare = df['fare_amount'].quantile(0.75)
IQR_fare = Q3_fare - Q1_fare
lower_bound_fare = Q1_fare - 1.5 * IQR_fare
upper_bound_fare = Q3_fare + 1.5 * IQR_fare
df = df[(df['fare_amount'] >= lower_bound_fare) & (df['fare_amount'] <= upper_bound_fare)]

# Remove outliers from 'distance_km'
Q1_distance = df['distance_km'].quantile(0.25)
Q3_distance = df['distance_km'].quantile(0.75)
IQR_distance = Q3_distance - Q1_distance
lower_bound_distance = Q1_distance - 1.5 * IQR_distance
upper_bound_distance = Q3_distance + 1.5 * IQR_distance
df = df[(df['distance_km'] >= lower_bound_distance) & (df['distance_km'] <= upper_bound_distance)]

print("DataFrame shape after removing outliers:", df.shape)
print("\nDataFrame head after removing outliers:")
df.head()

df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['day_of_week_sin'] = np.sin(2 * np.pi * df['day_of_week'] / 7)
df['day_of_week_cos'] = np.cos(2 * np.pi * df['day_of_week'] / 7)
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)
df.drop(["hour", "day_of_week", "month"],axis=1,inplace=True)
df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.decomposition import PCA # Keep PCA for general understanding, but remove its LR combination as it wasn't requested to be re-run
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis # For explanation
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor # New model import
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

def apply_ml_models(data_df):
    print("--- Starting ML Model Application with new models ---")

    # Define features (X) and target (y)
    X = data_df.drop('fare_amount', axis=1)
    y = data_df['fare_amount']

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print(f"Training data shape: {X_train.shape}")
    print(f"Testing data shape: {X_test.shape}")

    # 1. Linear Regression (re-run for comparison)
    print("\n--- Applying Linear Regression ---")
    lr_model = LinearRegression()
    lr_model.fit(X_train, y_train)
    y_pred_lr = lr_model.predict(X_test)
    r2_lr = r2_score(y_test, y_pred_lr)
    mse_lr = mean_squared_error(y_test, y_pred_lr)
    print(f"Linear Regression R-squared: {r2_lr:.4f}")
    print(f"Linear Regression MSE: {mse_lr:.4f}")

    # 2. Support Vector Regressor (SVR) (re-run for comparison)
    print("\n--- Applying Support Vector Regressor (SVR) ---")
    print("Note: SVR can be very slow on large datasets. Using a small sample for demonstration.")
    sample_size = min(5000, len(X_train))
    sample_indices = np.random.choice(len(X_train), sample_size, replace=False)
    X_train_sample = X_train.iloc[sample_indices]
    y_train_sample = y_train.iloc[sample_indices]

    svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1) # RBF kernel is common
    svr_model.fit(X_train_sample, y_train_sample)
    y_pred_svr = svr_model.predict(X_test)
    r2_svr = r2_score(y_test, y_pred_svr)
    mse_svr = mean_squared_error(y_test, y_pred_svr)
    print(f"SVR R-squared (on sampled data for training): {r2_svr:.4f}")
    print(f"SVR MSE (on sampled data for training): {mse_svr:.4f}")

    # 3. Random Forest Regressor
    print("\n--- Applying Random Forest Regressor ---")
    rf_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=10)
    rf_model.fit(X_train, y_train)
    y_pred_rf = rf_model.predict(X_test)
    r2_rf = r2_score(y_test, y_pred_rf)
    mse_rf = mean_squared_error(y_test, y_pred_rf)
    print(f"Random Forest Regressor R-squared: {r2_rf:.4f}")
    print(f"Random Forest Regressor MSE: {mse_rf:.4f}")

    # 4. XGBoost Regressor
    print("\n--- Applying XGBoost Regressor ---")
    xgb_model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42, n_jobs=-1, max_depth=5)
    xgb_model.fit(X_train, y_train)
    y_pred_xgb = xgb_model.predict(X_test)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    print(f"XGBoost Regressor R-squared: {r2_xgb:.4f}")
    print(f"XGBoost Regressor MSE: {mse_xgb:.4f}")

    # 5. LightGBM Regressor (New Model)
    print("\n--- Applying LightGBM Regressor ---")
    lgbm_model = LGBMRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=8,
        num_leaves=31,
        random_state=42,
        n_jobs=-1
    )
    lgbm_model.fit(X_train, y_train)
    y_pred_lgbm = lgbm_model.predict(X_test)
    r2_lgbm = r2_score(y_test, y_pred_lgbm)
    mse_lgbm = mean_squared_error(y_test, y_pred_lgbm)
    print(f"LightGBM Regressor R-squared: {r2_lgbm:.4f}")
    print(f"LightGBM Regressor MSE: {mse_lgbm:.4f}")


apply_ml_models(df)

"""## Hyperparameter Tuning for XGBoost Regressor"""

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Redefine features (X) and target (y) from the current global df
X = df.drop('fare_amount', axis=1)
y = df['fare_amount']

# Split data into training and testing sets (matching the split in apply_ml_models for consistency)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape for tuning: {X_train.shape}")
print(f"Testing data shape for tuning: {X_test.shape}")

# Parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': [200, 400, 600, 800],
    'max_depth': [4, 6, 8, 10],
    'learning_rate': [0.01, 0.03, 0.05, 0.1],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'reg_alpha': [0, 0.1, 1],
    'reg_lambda': [1, 1.5, 2]
}

# Initialize RandomizedSearchCV
search = RandomizedSearchCV(
    XGBRegressor(random_state=42, n_jobs=-1),
    param_distributions=param_dist,
    n_iter=30, # Number of parameter settings that are sampled
    cv=3,       # Number of folds for cross-validation
    scoring='r2',
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Fit RandomizedSearchCV to the training data
print("\n--- Starting RandomizedSearchCV for XGBoost ---")
search.fit(X_train, y_train)

# Print the best parameters found
print("\nBest parameters found by RandomizedSearchCV:")
print(search.best_params_)

# Evaluate the model with the best parameters
print("\n--- Evaluating XGBoost Regressor with best parameters ---")
final_xgb_model = XGBRegressor(**search.best_params_, random_state=42, n_jobs=-1)
final_xgb_model.fit(X_train, y_train)
y_pred_final_xgb = final_xgb_model.predict(X_test)

r2_final_xgb = r2_score(y_test, y_pred_final_xgb)
mse_final_xgb = mean_squared_error(y_test, y_pred_final_xgb)

print(f"XGBoost Regressor (Tuned) R-squared: {r2_final_xgb:.4f}")
print(f"XGBoost Regressor (Tuned) MSE: {mse_final_xgb:.4f}")

import joblib

# 1. حفظ الـ Scaler الذي تم تدريبه على الـ Coordinates
joblib.dump(scaler, 'coordinates_scaler.pkl')
print("Saved Scaler successfully!")

# 2. حفظ الموديل النهائي بعد الـ Tuning
# تأكد أن اسم الموديل النهائي هو final_xgb_model كما في كودك
joblib.dump(final_xgb_model, 'uber_xgb_model.pkl')
print("Saved Tuned XGBoost Model successfully!")

